apps/ref_home/urls.py
from django.conf.urls import url
from . import views

app_name='main'
urlpatterns = [
	url(r'^home$', views.index, name='home'),
	url(r'^refs$', views.refs, name='refs'),
	url(r'^rules$', views.rules, name='rules'),
	url(r'^logout$', views.logout, name='logout')
]

apps/team/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^team_gen$", views.gen, name="gen"),
	url(r"^gen_data/", views.gen_data, name="gen_data"),
	url(r"^assignPlayers$", views.assignPlayers, name="assignPlayers"),
	# url(r"^)
]

fantasy_ref/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^ref', include('apps.ref_home.urls', namespace='main')),
    url(r'^league', include('apps.league.urls', namespace='league')),
    url(r'^team', include('apps.team.urls', namespace='team')),

]

apps/ref_home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.


class Ref(models.Model):
	name = models.CharField(max_length=200)
	games = models.IntegerField()
	available = models.BooleanField(default=True)
	createdAt = models.DateTimeField(auto_now_add=True)
	updatedAt = models.DateTimeField(auto_now=True)

apps/ref_home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from ..login.models import User

# Create your views here.
def index(request):
	# print '**REF_HOME**' * 250
	user = User.objects.get(id=request.session.get('id'))
	context = {
		'user': user
	}	
	return render(request, 'ref_home/index.html', context)

def refs(request):
	# print '**REFS**' * 250
	
	return render(request, 'ref_home/refs.html')

def rules(request):
	# print '**RULES**' * 250
	return render(request, 'ref_home/rules.html')

def logout(request):
    request.session.flush()
    messages.success(request, 'Logged Out')
    return redirect('login:index')

apps/ref_home/templates/ref_home/index.html
<html>
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>Home</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
</head>
<body>
	<a href="{% url 'main:refs' %}">Ref Data</a>
	<a href="{% url 'team:gen' %}">Teams and players</a>
	<a href="{% url 'main:rules' %}">How to Play</a>
	<a href="{% url 'main:logout' %}">Logout</a>

	<h1>Welcome {{user.username}}</h1>
	<h3>Would you just look at that</h3>


</body>
</html>

apps/ref_home/templates/ref_home/rules.html
<html>
<head>
  {% load staticfiles %}
	<meta charset="UTF-8">
	<title>Rules</title>
  <link rel="stylesheet" href="{% static 'ref_home/css/rules.css' %}">
</head>
<body>
  <a href="{% url 'main:logout' %}">Logout</a>
  <a href="{% url 'main:home' %}">Home</a>
	<h1>How to Play</h1>
  <section id='rules'>
    <p>The basics of the game are the same as any other fantasy sports game. Only here we could careless about who scores the most point runs, who wins game event, or who wins the cup trophy. There's no keeping track of how many players touch home plate during the extra point attempt or the Touchdown was made from the 3-point line. You care about the Refs and how many penalties they issue in each game.</p>
    <p>You will draft refs from the available refs for the league onto your roster and assign them to either Active or Benched for the week. Depending on the size of each league each player will have 3, 5, or 7 refs. 5 and 7 ref leagues will have 2 or 3 refs benched each week when 3 ref leagues will bench only one.</p>
  </section>
	<section class="topText">
    <ul class="head" ><h3>How it Works</h3>
      <li id="sections"><h4>Earning Points:</h4>
        <ul id="sectText">
          <li>5 Yrd Penalty ---> 1 point</li>
          <li>10 Yrd Penalty ---> 2 points</li>
          <li>15 Yrd Penalty ---> 3 points</li>
          <li>Half the Distance to the Goal --> 3 points</li>
          <li>Player Get in the Face of Your Ref --> 2 points</li>
        </ul>
      </li>
      <li id="sections"><h4>Point Multipliers:</h4>
        <ul id="sectText">
          <li>Crowd "Boo" so Loud that the Ref Cannot be Heard --> x2 points(applies to points earned on penalty called)</li>
          <li>Head Ref for Monday Night Football --> x1.5 points (applies to total points earned from game)</li>
          <li>Head Ref for Division Game --> x1.25 point (applies to total points earned from game)</li>
          <li>Head Ref for Conference Game --> x1.5 points (applies to total points earned from game)</li>
          <li>Head Ref for Super Bowl --> x2 points(applies to total points earned from game)</li>
        </ul>
      </li>
      <li id="sections"><h4>Loss of Points:</h4>
        <ul id="sectText">
          <li>Sports Commintators Make Fun of Your Ref --> -1 point</li>
          <li>Ref Knocked Over By Player --> -2 points</li>
          <li>Your Refs Call is Challenged AND Overturned --> Lose all current points for game</li>
        </ul>
      </li>
    </ul>
	</section>
</body>
</html>