apps/login/urls.py
from django.conf.urls import url
from . import views

app_name='login'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login$', views.login, name='login'),
	url(r'^register$', views.register, name='register'),
	url(r'^success$', views.success, name='success')
]

fantasy_ref/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^ref', include('apps.ref_home.urls', namespace='main')),
    url(r'^league', include('apps.league.urls', namespace='league')),
    url(r'^team', include('apps.team.urls', namespace='team')),

]

apps/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

# Create your models here.
class UserManager(models.Manager):
	def authUser(self, postData):
		results = {'status': True, 'errors': [], 'user': None}
		if not postData['first_name'] or len(postData['first_name']) < 2:
			results['status'] = False
			results['errors'].append('Invalid Name. Get it right. Everybody gets one...')
		if not postData['last_name'] or len(postData['last_name']) < 2:
			results['status'] = False
			results['errors'].append('Invalid Last Name. You\'re skating on thin ice there buck-o')
		if not postData['username'] or len(postData['username']) < 2:
			results['status'] = False
			results['errors'].append('You can come up with a better username than that.')
		if not postData['email'] or not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", postData['email']):
			results['status'] = False
			results['errors'].append('please use a real email, im not running this on Hilary Clintons server bud')
		if not postData['password'] or len(postData['password']) < 8:
			results['status'] = False
			results['errors'].append('Password is weaker than a college students feels')
		if postData['confPassword'] != postData['password']:
			results['status'] = False
			results['errors'].append('Is it really too hard to make the two passwords match.........')
		if results['status'] is False:
			return results 

		user = User.objects.filter(username=postData['username'])

		if user:
			results['status'] = False
			results['errors'].append('Everything went horrifically wrong, run away now!!!!!!!!')

		if results['status']:
			hashpassword = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			user = User.objects.create(
										first_name = postData['first_name'],
										last_name = postData['last_name'],
										username = postData['username'],
										email = postData['email'],
										password = hashpassword
										)
			results['user'] = user
		return results

	def loginUser(self, postData):
		results = {'status': True, 'errors': [], 'user': None}
		user = User.objects.filter(username=postData['username'])

		try:
			user[0]
		except IndexError:
			results['status'] = False
			results['errors'].append('OH GOD NO ITS FAILING.... call I.T. NOW!!!!')

		if user[0]:
			if user[0].password != bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()):
				results['status'] = False
				results['errors'].append('Username or Password are invalid. notifing authorities on your location')
			else:
				results['user'] = user[0].id
		else:
			results['status'] = False
		return results

class User(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	username = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.id) + ", " + self.username

	objects = UserManager()

apps/login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User


def index(request):
	# print '**INDEX**' * 500
	return render(request, 'login/index.html')

def login(request):
	# print '**LOGIN**' * 500
	results = User.objects.loginUser(request.POST)
	if results['status'] is False:
		for error in results['errors']:
			messages.error(request, error)
		return redirect('login:index')
	else:
		user = User.objects.get(id=results['user'])
		request.session['id'] = user.id
	return redirect('login:success')

def register(request):
	# print '**REGISTER**' * 500
	results = User.objects.authUser(request.POST)
	if not results['status']:
		for error in results['errors']:
			messages.error(request, error)
			return redirect('login:index')
	request.session['id'] = results['user'].id
	return redirect('login:success')

def success(request):
	# print '**SUCCESS**' * 500
	user = User.objects.get(id=request.session.get('id'))
	context = {
		'user': user
	}
	return redirect('main:home')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fantasy Refs</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login/css/index.css' %}">
  </head>
  <body>

    <h1>Fantasy Referees</h1>
    <!-- <p>Here we have a fantasy football style league but instead of player you earn points based on hte refs and penalties given</p> -->
    <p>Join the most Exciting Fantasy Sports game that has nothing really to do with sports!!!</p>
    
    

    <h3>Want to Register or already a member?</h3>
    {% if messages %}
    <ul id="messages">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <div>
      <h3>Login</h3>
      <form id="logForm" action="{% url 'login:login' %}" method="post">
        {% csrf_token %}
        Username: <input type="text" name="username">
        Password: <input type="password" name="password">
        <input type="submit" name="submit" value="Login">
      </form>
      <h3>Register</h3>
      <form id="regForm" action="{% url 'login:register' %}" method="post">
        {% csrf_token %}
        First Name: <input type="text" name="first_name" value=""/><br><br>
        Last Name: <input type="text" name="last_name"><br><br>
        Username: <input type="text" name="username" value=""/><br><br>
        Email: <input type="text" name="email" value=""/><br><br>
        Password: <input type="password" name="password" value=""/><br><br>
        Confirm Password: <input type="password" name="confPassword" value=""/><br><br>
        <input type="submit" name="submit" value="Register"/>
      </form>
    </div>
  </body>
</html