apps/team/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r"^team_gen$", views.gen, name="gen"),
	url(r"^gen_data/", views.gen_data, name="gen_data"),
	url(r"^assignPlayers$", views.assignPlayers, name="assignPlayers"),
	# url(r"^)
]

fantasy_ref/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^ref', include('apps.ref_home.urls', namespace='main')),
    url(r'^league', include('apps.league.urls', namespace='league')),
    url(r'^team', include('apps.team.urls', namespace='team')),

]

apps/team/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Team(models.Model):
	location = models.CharField(max_length=50)
	team_name = models.CharField(max_length=50)


class Player(models.Model):
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	curr_team = models.ForeignKey(Team, related_name="current_players")
	all_teams = models.ManyToManyField(Team, related_name="all_players")

apps/team/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Team, Player

from . import team_generator

def gen(request):
	context = {
		"teams": Team.objects.all(),
		"players": Player.objects.all(),
	}
	return render(request, "team/index.html", context)


def gen_data(request):
	team_generator.team_generate(50)
	team_generator.player_generation(200)

	return redirect('team:gen')

def assignPlayers(request):
	print "***assignPlayers***" * 25

apps/team/templates/team/index.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
	<title>Teams and Players</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/teams.css' %}">
</head>
<body>
	<h1>Teams</h1>
	<ol>
		{% for team in teams %}
			<li>{{team.location}}
				{{team.team_name}}</li>
		{% empty %}
			<p>No teams found. Try <code>python manage.py loaddata data.json</code>, or, if that doesn't work, going <a href="{% url 'team:gen_data' %}">here</a></p>
		{% endfor %}
	</ol>
	<h1>Players</h1>
	<ol>
		{% for player in players %}
			<li>{{player.first_name}}
				{{player.last_name}}</li>
		{% empty %}
			<p>No players found. Try <code>python manage.py loaddata data.json</code>, or, if that doesn't work, going <a href="{% url 'team:gen_data' %}">here</a></p>
		{% endfor %}
	</ol>
</body>
</html>